apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}